/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsDate,
  IsInt,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { LikeUpdateManyWithoutVideosInput } from "./LikeUpdateManyWithoutVideosInput";
import { CommentUpdateManyWithoutVideosInput } from "./CommentUpdateManyWithoutVideosInput";

@InputType()
class VideoUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  uploadDate?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fileUrl?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  views?: number | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => LikeUpdateManyWithoutVideosInput,
  })
  @ValidateNested()
  @Type(() => LikeUpdateManyWithoutVideosInput)
  @IsOptional()
  @Field(() => LikeUpdateManyWithoutVideosInput, {
    nullable: true,
  })
  likes?: LikeUpdateManyWithoutVideosInput;

  @ApiProperty({
    required: false,
    type: () => CommentUpdateManyWithoutVideosInput,
  })
  @ValidateNested()
  @Type(() => CommentUpdateManyWithoutVideosInput)
  @IsOptional()
  @Field(() => CommentUpdateManyWithoutVideosInput, {
    nullable: true,
  })
  comments?: CommentUpdateManyWithoutVideosInput;
}

export { VideoUpdateInput as VideoUpdateInput };
